apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
android {
    compileSdkVersion 31
    defaultConfig {
        minSdkVersion 19
        targetSdkVersion 31
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }
    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            minifyEnabled false
            shrinkResources false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    namespace 'com.mayan.sospluginmodlue'
}
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.recyclerview:recyclerview:1.2.1'
    implementation "com.ethanhua:skeleton:$rootProject.ext.skeleton"
    implementation "io.supercharge:shimmerlayout:$rootProject.ext.shimmerlayout"
    implementation "com.squareup.retrofit2:retrofit:$rootProject.ext.retrofit"
    implementation "com.squareup.retrofit2:converter-gson:$rootProject.ext.converter_gson"
    implementation "com.squareup.okhttp3:logging-interceptor:$rootProject.ext.interceptor"
    implementation "jp.wasabeef:recyclerview-animators:$rootProject.ext.animator"
    implementation "com.google.android.gms:play-services-location:$rootProject.ext.location"
    implementation "com.google.android.gms:play-services-maps:$rootProject.ext.maps"
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.0'
    implementation 'com.google.android.material:material:1.2.1'

    implementation "com.squareup.picasso:picasso:$rootProject.ext.picasso"
}
/*
ext {
    retrofit = '2.3.0'
    converter_gson = '2.3.0'
    interceptor = '3.8.1'
    maps = '15.0.0'
}*/
